---
kind: pipeline
type: kubernetes
name: build
platform:
  os: linux
  arch: amd64

steps:
- name: formatting-check
  image: golang
  commands:
  - test -z $(gofmt -l .)
- name: build
  image: docker
  commands:
  - docker build -f Dockerfile .
---
kind: pipeline
type: kubernetes
name: deploy
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker
  commands:
  - echo "$DOCKER_PASSWORD" | docker login "docker.zvon.tech" -u "$DOCKER_USERNAME" --password-stdin