---
kind: pipeline
type: kubernetes
name: deploy
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker
  environment:
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - echo "$DOCKER_USERNAME"
  - docker login "docker.zvon.tech" --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"