---
kind: pipeline
type: kubernetes
name: build
platform:
  os: linux
  arch: amd64

steps:
- name: formatting-check
  image: golang
  commands:
  - test -z $(gofmt -l .)
- name: build
  image: docker
  commands:
  - docker build
---
kind: pipeline
type: kubernetes
name: deploy
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker
  commands:
  - docker login "docker.zvon.tech" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker buildx create --use
  - docker buildx build -f Dockerfile -t "docker.zvon.tech/lunch-go:${DRONE_TAG}" --platform linux/amd64,linux/arm64 --push .