---
kind: pipeline
type: kubernetes
name: deploy
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker
  commands:
  - echo "$DOCKER_USERNAME"
  - echo "$DOCKER_PASSWORD" | docker login "docker.zvon.tech" --username "$DOCKER_USERNAME" --password-stdin